/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SmartApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: 'My Smart App',
                    items: [
                        {
                            xtype: 'gridpanel',
                            title: 'User Data',
                            store: 'userStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'userid',
                                    text: 'User ID',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'firstname',
                                    text: 'First Name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastname',
                                    text: 'Last Name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'phone',
                                    text: 'Phone',
                                    flex: 1
                                }
                            ],
                            listeners: {
                                boxready: {
                                    fn: me.onGridpanelBoxReady,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelBoxReady: function(component, width, height, eOpts) {
        testExampleService.getUsersFromDB(
            function(res){
                var userStore = Ext.StoreMgr.lookup('userStore');

                userStore.removeAll();

                var userList = res;

                var arr = [];
                for(var i = 0; i < userList.length; i++){


                    var user = userList[i];
                    var newRecord = Ext.create('SmartApp.model.User',{
                        firstname: user.firstName,
                        lastname: user.lastName,
                        phone: user.phone,
                        userid: user.userId
                    });

                    arr.push(newRecord);

                }

                userStore.loadData(arr);
            }
        );
    }

});